export const PERMISSIONS = [
  'tenant:organizations:create',
  'tenant:staff:read',
  'tenant:staff:manage',
  'org:organizations:read',
  'org:organizations:update',
  'org:organizations:delete',
  'org:masters:read',
  'org:masters:update',
  'org:users:read',
  'org:users:manage',
  'org:integrations:read',
  'org:integrations:manage',
  'org:integrations:sync',
  'org:sync:read',
  'org:sync:run',
  'org:agent_runs:read',
  'org:budgets:read',
  'org:budgets:update',
  'org:actuals:read',
  'org:actuals:import',
  'org:cashflow:read',
  'org:cashflow:manage',
  'org:reports:read',
  'org:comments:read',
  'org:comments:manage',
  'org:actions:read',
  'org:actions:manage',
  'org:business_events:read',
  'org:business_events:manage',
  'org:calendar:read',
  'org:calendar:manage',
  'org:monthly_close:read',
  'org:monthly_close:manage',
  'org:monthly_review:read',
  'org:monthly_review:manage',
  'org:cashflow_certainty:read',
  'org:cashflow_certainty:manage',
  'org:insights:read',
  'org:ai:run',
  'org:briefing:read',
  'org:briefing:manage',
  'org:notifications:read',
  'org:mf:read',
  'org:simulation:read',
  'org:onboarding:read',
  'org:onboarding:manage',
  'org:risk_findings:read',
  'org:risk_findings:manage',
  'org:risk_findings:scan',
  'org:chosho:read',
  'org:chosho:manage',
  'org:journal_review:read',
  'org:journal_review:manage',
  // 決算検討 (year-end-review) 共有データ
  'org:year_end_review:read',
  'org:year_end_review:manage',
  // ロカベン 状態 (顧問先全体で共有)
  'org:locaben:read',
  'org:locaben:manage',
  // 汎用 feature state (上記以外のセクション)
  'org:feature_state:read',
  'org:feature_state:write',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const TENANT_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  firm_owner: [
    'tenant:organizations:create',
    'tenant:staff:read',
    'tenant:staff:manage',
    'org:organizations:read',
    'org:organizations:update',
    'org:organizations:delete',
    'org:masters:read',
    'org:masters:update',
    'org:users:read',
    'org:users:manage',
    'org:integrations:read',
    'org:integrations:manage',
    'org:integrations:sync',
    'org:sync:read',
    'org:sync:run',
    'org:agent_runs:read',
    'org:budgets:read',
    'org:budgets:update',
    'org:actuals:read',
    'org:actuals:import',
    'org:cashflow:read',
    'org:cashflow:manage',
    'org:reports:read',
    'org:comments:read',
    'org:comments:manage',
    'org:actions:read',
    'org:actions:manage',
    'org:business_events:read',
    'org:business_events:manage',
    'org:calendar:read',
    'org:calendar:manage',
    'org:monthly_close:read',
    'org:monthly_close:manage',
    'org:monthly_review:read',
    'org:monthly_review:manage',
    'org:cashflow_certainty:read',
    'org:cashflow_certainty:manage',
    'org:insights:read',
    'org:ai:run',
    'org:briefing:read',
    'org:briefing:manage',
    'org:notifications:read',
    'org:mf:read',
    'org:simulation:read',
    'org:onboarding:read',
    'org:onboarding:manage',
    'org:risk_findings:read',
    'org:risk_findings:manage',
    'org:risk_findings:scan',
    'org:chosho:read',
    'org:chosho:manage',
    'org:journal_review:read',
    'org:journal_review:manage',
    'org:year_end_review:read',
    'org:year_end_review:manage',
    'org:locaben:read',
    'org:locaben:manage',
    'org:feature_state:read',
    'org:feature_state:write',
  ],
  firm_admin: [
    'tenant:organizations:create',
    'org:organizations:read',
    'org:organizations:update',
    'org:masters:read',
    'org:masters:update',
    'org:users:read',
    'org:users:manage',
    'org:integrations:read',
    'org:integrations:manage',
    'org:integrations:sync',
    'org:sync:read',
    'org:sync:run',
    'org:agent_runs:read',
    'org:budgets:read',
    'org:budgets:update',
    'org:actuals:read',
    'org:actuals:import',
    'org:cashflow:read',
    'org:cashflow:manage',
    'org:reports:read',
    'org:comments:read',
    'org:comments:manage',
    'org:actions:read',
    'org:actions:manage',
    'org:business_events:read',
    'org:business_events:manage',
    'org:calendar:read',
    'org:calendar:manage',
    'org:monthly_close:read',
    'org:monthly_close:manage',
    'org:monthly_review:read',
    'org:monthly_review:manage',
    'org:cashflow_certainty:read',
    'org:cashflow_certainty:manage',
    'org:insights:read',
    'org:ai:run',
    'org:briefing:read',
    'org:briefing:manage',
    'org:notifications:read',
    'org:mf:read',
    'org:simulation:read',
    'org:onboarding:read',
    'org:onboarding:manage',
    'org:risk_findings:read',
    'org:risk_findings:manage',
    'org:risk_findings:scan',
    'org:chosho:read',
    'org:chosho:manage',
    'org:journal_review:read',
    'org:journal_review:manage',
    'org:year_end_review:read',
    'org:year_end_review:manage',
    'org:locaben:read',
    'org:locaben:manage',
    'org:feature_state:read',
    'org:feature_state:write',
  ],
  // Current SevenBoard behavior lets advisors create a new client and assigns
  // them to it. Keep that during the migration to scoped memberships.
  firm_advisor: [
    'tenant:organizations:create',
    'org:risk_findings:read',
    'org:risk_findings:manage',
    'org:risk_findings:scan',
    'org:chosho:read',
    'org:chosho:manage',
    'org:journal_review:read',
    'org:journal_review:manage',
    'org:year_end_review:read',
    'org:year_end_review:manage',
    'org:locaben:read',
    'org:locaben:manage',
    'org:feature_state:read',
    'org:feature_state:write',
  ],
  // Team-scoped manager access needs Team/Assignment models. Keep it closed
  // until that scope exists instead of silently granting tenant-wide access.
  firm_manager: [],
  firm_viewer: [
    'org:organizations:read',
    'org:masters:read',
    'org:users:read',
    'org:integrations:read',
    'org:sync:read',
    'org:budgets:read',
    'org:actuals:read',
    'org:cashflow:read',
    'org:reports:read',
    'org:comments:read',
    'org:actions:read',
    'org:business_events:read',
    'org:calendar:read',
    'org:monthly_close:read',
    'org:monthly_review:read',
    'org:cashflow_certainty:read',
    'org:insights:read',
    'org:briefing:read',
    'org:notifications:read',
    'org:mf:read',
    'org:simulation:read',
    'org:onboarding:read',
    'org:risk_findings:read',
    'org:chosho:read',
    'org:journal_review:read',
    'org:year_end_review:read',
    'org:locaben:read',
    'org:feature_state:read',
  ],
};

export function roleHasPermission(
  role: string | null | undefined,
  permission: Permission,
): boolean {
  if (!role) return false;
  return TENANT_ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
